# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1078c505640194ad4192fb69531cb2aee0697cebeac5c33492217ca97a27026ab1366827fecb3bcccafbd03ac44c875db4e3813bd9dd54e7b0cee509beee2c54

test:
  secret_key_base: e25f4dda3d281241c534b0185f6e49961fa0d9e562cf84f62d46027216bf0b6650c89e854a7feb61c14cd4e928329d8aa46a27436f3b6cfb10e5b8f42df92774

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
